### ISSUE TITLE
npm install 오류

### ISSUE THREAD

**Issue by pleiadex** [kkagill/addition-game-starter#1]
안녕하세요, 

저는 서성윤이고, 인프런에 올려주신 클레이튼 BApp 개발 실습 잘 보고 있습니다.

먼저 이렇게 값진 강의 공유해주셔서 감사의 말씀 드립니다.

그런데, 제가 "Baobab에 스마트 컨트랙트 배포 1" 강좌에서 VScode terminal에서 npm install을 하였는데 오류가 발생하였습니다.

오류가 어떤 것을 말하는지 몰라 검색을 했는데도 해결하지 못하여 이렇게 이슈 남깁니다.

오류는 아래 사진과 같고, 혹시 발생 가능한 오류에 대해서 조언해주시면 정말 감사하겠습니다.

![image](https://user-images.githubusercontent.com/37097363/61106286-a07c9380-a4b7-11e9-87ea-7e8c011dfb92.png)

이 오류 해결 후에, 이후 강좌까지 완강하겠습니다.

감사합니다.

서성윤 올림.

**Comment by pleiadex** [comment]
python 버전 문제 해결하니까 설치 되었습니다.

혹시 비슷한 문제 있으신 분들은 아래 command 참고하시면 될 듯 해요 :)

npm install --global --production windows-build-tools



감사합니다.

서성윤 올림.

**Comment by kkagill** [comment]
네 감사합니다. 해당 오류는 인프런강좌 질문란에 해결법과 함께 이미 많이 공지되었습니다.

2019년 7월 12일 (금) 오전 12:07, SungYounSeo <notifications@github.com>님이 작성:
